export enum SessionStatus {
    IDLE = "IDLE",
    STARTING = "STARTING",
    RUNNING = "RUNNING",
    STOPPING = "STOPPING",
    STOPPED = "STOPPED",
    ERROR = "ERROR",
}

export enum SessionEvent {
    USER_SPEECH_START = "USER_SPEECH_START",
    USER_SPEECH_END = "USER_SPEECH_END",
    AGENT_SPEECH_START = "AGENT_SPEECH_START",
    AGENT_SPEECH_END = "AGENT_SPEECH_END",
    INTERRUPT = "INTERRUPT",
    ERROR = "ERROR",
}
